from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (SimpleDocTemplate, Paragraph, 
                                  Spacer, Table, TableStyle)
from reportlab.lib.units import inch
import io
from datetime import datetime

def generate_pdf_report(analysis_result, filename="report.pdf"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    
    
    story.append(Paragraph(
        "DeepTrace — Forensic Analysis Report", 
        styles['Title']
    ))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles['Normal']
    ))
    story.append(Spacer(1, 0.3*inch))
    
    # Authenticity Score
    auth = analysis_result['authenticity']
    story.append(Paragraph(
        f"Overall Authenticity Score: {auth['score']}% — Risk: {auth['risk'].upper()}",
        styles['Heading2']
    ))
    story.append(Spacer(1, 0.2*inch))
    
    
    story.append(Paragraph("Suspicion Breakdown", styles['Heading2']))
    breakdown = analysis_result['breakdown']
    table_data = [
        ['Signal', 'Score', 'Status'],
        ['Blink Anomaly', str(breakdown['blink']), 
         'Suspicious' if breakdown['blink'] > 0.6 else 'Normal'],
        ['Lip Sync Mismatch', str(breakdown['lip_sync']),
         'Suspicious' if breakdown['lip_sync'] > 0.6 else 'Normal'],
        ['Feature Drift', str(breakdown['feature_drift']),
         'Suspicious' if breakdown['feature_drift'] > 0.6 else 'Normal'],
    ]
    
    table = Table(table_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2D2D2D')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), 
         [colors.HexColor('#F5F5F5'), colors.white]),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.3*inch))
    
   
    story.append(Paragraph("Detected Manipulation Segments", 
                            styles['Heading2']))
    segs = analysis_result.get('fake_segments', [])
    
    if segs:
        seg_data = [['Start Time', 'End Time', 'Confidence']]
        for seg in segs:
            seg_data.append([
                f"{seg['start']}s",
                f"{seg['end']}s",
                f"{round(seg['avg_confidence']*100, 1)}%"
            ])
        seg_table = Table(seg_data, 
                          colWidths=[2*inch, 2*inch, 2*inch])
        seg_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#C0392B')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('ROWBACKGROUNDS', (0,1), (-1,-1),
             [colors.HexColor('#FDECEA'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(seg_table)
    else:
        story.append(Paragraph("No manipulation segments detected.",
                                styles['Normal']))
    
    story.append(Spacer(1, 0.3*inch))
    
    
    story.append(Paragraph("Analysis Findings", styles['Heading2']))
    for reason in analysis_result.get('reasons', []):
        story.append(Paragraph(f"• {reason}", styles['Normal']))
    
   
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(
        "This report was generated by DeepTrace — Temporal Deepfake Forensic Analyzer",
        styles['Normal']
    ))
    
    doc.build(story)
    buffer.seek(0)
    return buffer